# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        cfg:
        - {os: windows-latest, python-version: '3.9', architecture: x64}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.cfg.python-version }} ${{ matrix.cfg.architecture }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel twine pyinstaller~=5.6 build

    - name: Setup
      run: |
        export BDISTWHEELFREEZELIBS=true
        python -m build
        python -m pip install dist/amulet_map_editor-*.whl --upgrade

    - name: PyInstaller build
      run: |
        python -m PyInstaller -y Amulet.spec
