name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel pyinstaller~=5.6 build

    - name: Setup
      run: |
        export BDISTWHEELFREEZELIBS=true
        python -m build
        python -m pip install dist/amulet_map_editor-*.whl --upgrade

    - name: PyInstaller build
      run: |
        python -m PyInstaller -y Amulet.spec

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Automated release for commit ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/Amulet/amulet_app.exe
        asset_name: amulet-map-editor-v${{ github.run_number }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable
